---
external_components:
  source: components # Build with local code instead of pulling from Github

substitutions:
  name: "hvac"
  friendly_name: "HVAC"
  device_description: "HVAC"
  logger_level: DEBUG
  tx_pin: GPIO6
  rx_pin: GPIO5
  board: m5stack-atoms3
  variant: esp32s3
  framework: esp-idf
  ct_version: 2

packages:
  comfortnet: !include comfortnet_base.yaml
  # Uncomment the devices you have on your network
  comfortnet-thermostat: !include comfortnet_thermostat.yaml
  comfortnet-furnace: !include comfortnet_furnace.yaml
  comfortnet-heat-pump: !include comfortnet_heat_pump.yaml

# Enable Home Assistant API
api:
  encryption:
    key: !secret hvac_monitor_api_key

ota:
  - platform: esphome
    password: !secret hvac_monitor_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "HVAC Fallback Hotspot"
    password: !secret fallback_wifi_password
